### ISSUE TITLE
[2.1.0] GLPI 9.2.2 - unable to login to GLPI with this version

### ISSUE THREAD

**Issue by tsmr** [pluginsGLPI/tag#39]
Php-errors : 

```2018-03-13 12:02:01 [@srv-glpi-prod]
  *** PHP Notice(8): Constant DO_NOT_CHECK_HTTP_REFERER already defined
  Backtrace :
  :                                                  
  front/cron.php:41                                  define()
  ...hare/php/Zend/Loader/StandardAutoloader.php:290 include()
  ...hare/php/Zend/Loader/StandardAutoloader.php:231 Zend\Loader\StandardAutoloader->loadClass()
  :                                                  Zend\Loader\StandardAutoloader->autoload()
  :                                                  spl_autoload_call()
  plugins/tag/inc/tag.class.php:579                  class_exists()
  plugins/tag/setup.php:96                           PluginTagTag::getCurrentItemtype()
  inc/plugin.class.php:145                           plugin_init_tag()
  inc/includes.php:119                               Plugin::load()
  front/cron.php:42                                  include()
2018-03-13 12:02:01 [@srv-glpi-prod]
  *** PHP Notice(8): Undefined variable: CFG_GLPI
  Backtrace :
  front/cron.php:87                                  
  ...hare/php/Zend/Loader/StandardAutoloader.php:290 include()
  ...hare/php/Zend/Loader/StandardAutoloader.php:231 Zend\Loader\StandardAutoloader->loadClass()
  :                                                  Zend\Loader\StandardAutoloader->autoload()
  :                                                  spl_autoload_call()
  plugins/tag/inc/tag.class.php:579                  class_exists()
  plugins/tag/setup.php:96                           PluginTagTag::getCurrentItemtype()
  inc/plugin.class.php:145                           plugin_init_tag()
  inc/includes.php:119                               Plugin::load()
  front/cron.php:42                                  include()
```
With modify in\tag.class.php with class_exists($itemtype, false) l579, it's resolved

**Comment by Stoatwblr** [comment]
+1 (also affected)

**Comment by cedric-anne** [comment]
I tried on GLPI 9.2.3 and I did not reproduce the problem. Could you check if you are still having the problem on 9.2.3 ?

**Comment by orthagh** [comment]
ping @tsmr

**Comment by cedric-anne** [comment]
Hi,

As I cannot reproduce, I assume the bug has been fixed in last versions.

Regards

**Comment by Stoatwblr** [comment]
I've verified that it's still there in 9.3 and with the newest version of tag - when it shows up, there are _2_ copies of the login page above each other - you can only see this if you scroll down. If you enter login and password on both then you can login.

This may be caused by interaction with other plugins.

**Comment by cedric-anne** [comment]
Hi @Stoatwblr ,

I cannot reproduce. Have you some other active plugins ? Which authentication method do you use ?

Regards

**Comment by amma35** [comment]
Hi,
The problem is not on windows but on linux.
We tested on an instance with only the plugin tag and we get these errors.

**Comment by Astrel-PF** [comment]
Hello @cedric-anne 

We are also affected by the bug, below are some detail : 
- GLPI version : 9.3.1
- Plugin version : 2.2.2

The issue remains even when all the plugins are disabled.
After enabling the plugin, the local authentication doesn't work anymore. We can't log in anymore and we have the double authentication page described by @Stoatwblr 

Except this login issue, it works !


If you need more detail, please let me know :-)
Thanks !

**Comment by cedric-anne** [comment]
Hi,

I still cannot reproduce this issue, so it cannot help. I'm using PHP 7.2 on Debian.

Can you try following patch (should fix initial issue, not sure it is related to login problem):
```diff
diff --git a/inc/tag.class.php b/inc/tag.class.php
index cf0b95c..238dca7 100644
--- a/inc/tag.class.php
+++ b/inc/tag.class.php
@@ -604,20 +604,18 @@ class PluginTagTag extends CommonDropdown {
                      $_SERVER['PHP_SELF'], $matches)) {
          $itemtype = 'plugin'.$matches[1].$matches[2];
 
-      } else if (preg_match('/([a-zA-Z]+).form.php/', $_SERVER['PHP_SELF'], $matches)) {
+      } else if (preg_match('/\/front\/([a-zA-Z]+).form.php/', $_SERVER['PHP_SELF'], $matches)) {
          $itemtype = $matches[1];
 
       } else if (preg_match('/\/plugins\/([a-zA-Z]+)\/front\/([a-zA-Z]+).php/',
                             $_SERVER['PHP_SELF'], $matches)) {
          $itemtype = 'plugin'.$matches[1].$matches[2];
 
-      } else if (preg_match('/([a-zA-Z]+).php/', $_SERVER['PHP_SELF'], $matches)) {
+      } else if (preg_match('/\/front\/([a-zA-Z]+).php/', $_SERVER['PHP_SELF'], $matches)) {
          $itemtype = $matches[1];
       }
 
-      if (!empty($itemtype)
-          && class_exists($itemtype)
-          && is_subclass_of($itemtype, "CommonDBTM")) {
+      if (!empty($itemtype) && is_subclass_of($itemtype, "CommonDBTM", true)) {
          // instanciate itemtype (to retrieve camelcase)
          $item = new $itemtype;
          return $item->getType();
```

**Comment by jframeau** [comment]
Hello,

patch applied but still not able to log in to GLPI when plugin activated.

Context:

- GLPI 9.3.2

- centos 7

- php 7.2

- firefox 63 / Chrome

**Extract from apache's logs when trying to log in:**

[2018-11-05 17:57:40] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Constant GLPI_ROOT already defined
  Backtrace :
  index.php:43                                       
  ...hare/php/Zend/Loader/StandardAutoloader.php:291 include()
  ...hare/php/Zend/Loader/StandardAutoloader.php:232 Zend\Loader\StandardAutoloader->loadClass()
  :                                                  Zend\Loader\StandardAutoloader->autoload()
  :                                                  spl_autoload_call()
  plugins/tag/inc/tag.class.php:623                  is_subclass_of()
  plugins/tag/setup.php:105                          PluginTagTag::getCurrentItemtype()
  inc/plugin.class.php:144                           plugin_init_tag()
  inc/includes.php:115                               Plugin::load()
  index.php:57                                       include()

[2018-11-05 17:57:40] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Constant DO_NOT_CHECK_HTTP_REFERER already defined
  Backtrace :
  index.php:47                                       
  ...hare/php/Zend/Loader/StandardAutoloader.php:291 include()
  ...hare/php/Zend/Loader/StandardAutoloader.php:232 Zend\Loader\StandardAutoloader->loadClass()
  :                                                  Zend\Loader\StandardAutoloader->autoload()
  :                                                  spl_autoload_call()
  plugins/tag/inc/tag.class.php:623                  is_subclass_of()
  plugins/tag/setup.php:105                          PluginTagTag::getCurrentItemtype()
  inc/plugin.class.php:144                           plugin_init_tag()
  inc/includes.php:115                               Plugin::load()
  index.php:57                                       include()

[2018-11-05 17:57:40] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined variable: CFG_GLPI
  Backtrace :
  index.php:75                                       
  ...hare/php/Zend/Loader/StandardAutoloader.php:291 include()
  ...hare/php/Zend/Loader/StandardAutoloader.php:232 Zend\Loader\StandardAutoloader->loadClass()
  :                                                  Zend\Loader\StandardAutoloader->autoload()
  :                                                  spl_autoload_call()
  plugins/tag/inc/tag.class.php:623                  is_subclass_of()
  plugins/tag/setup.php:105                          PluginTagTag::getCurrentItemtype()
  inc/plugin.class.php:144                           plugin_init_tag()
  inc/includes.php:115                               Plugin::load()
  index.php:57                                       include()

[2018-11-05 17:57:40] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined variable: CFG_GLPI
  Backtrace :
  index.php:79                                       
  ...hare/php/Zend/Loader/StandardAutoloader.php:291 include()
  ...hare/php/Zend/Loader/StandardAutoloader.php:232 Zend\Loader\StandardAutoloader->loadClass()
  :                                                  Zend\Loader\StandardAutoloader->autoload()
  :                                                  spl_autoload_call()
  plugins/tag/inc/tag.class.php:623                  is_subclass_of()
  plugins/tag/setup.php:105                          PluginTagTag::getCurrentItemtype()
  inc/plugin.class.php:144                           plugin_init_tag()
  inc/includes.php:115                               Plugin::load()
  index.php:57                                       include()

[2018-11-05 17:57:40] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined variable: CFG_GLPI
  Backtrace :
  index.php:86                                       
  ...hare/php/Zend/Loader/StandardAutoloader.php:291 include()
  ...hare/php/Zend/Loader/StandardAutoloader.php:232 Zend\Loader\StandardAutoloader->loadClass()
  :                                                  Zend\Loader\StandardAutoloader->autoload()
  :                                                  spl_autoload_call()
  plugins/tag/inc/tag.class.php:623                  is_subclass_of()
  plugins/tag/setup.php:105                          PluginTagTag::getCurrentItemtype()
  inc/plugin.class.php:144                           plugin_init_tag()
  inc/includes.php:115                               Plugin::load()
  index.php:57                                       include()

[2018-11-05 17:57:40] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined variable: CFG_GLPI
  Backtrace :
  index.php:89                                       
  ...hare/php/Zend/Loader/StandardAutoloader.php:291 include()
  ...hare/php/Zend/Loader/StandardAutoloader.php:232 Zend\Loader\StandardAutoloader->loadClass()
  :                                                  Zend\Loader\StandardAutoloader->autoload()
  :                                                  spl_autoload_call()
  plugins/tag/inc/tag.class.php:623                  is_subclass_of()
  plugins/tag/setup.php:105                          PluginTagTag::getCurrentItemtype()
  inc/plugin.class.php:144                           plugin_init_tag()
  inc/includes.php:115                               Plugin::load()
  index.php:57                                       include()

[2018-11-05 17:57:40] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined variable: CFG_GLPI
  Backtrace :
  index.php:104                                      
  ...hare/php/Zend/Loader/StandardAutoloader.php:291 include()
  ...hare/php/Zend/Loader/StandardAutoloader.php:232 Zend\Loader\StandardAutoloader->loadClass()
  :                                                  Zend\Loader\StandardAutoloader->autoload()
  :                                                  spl_autoload_call()
  plugins/tag/inc/tag.class.php:623                  is_subclass_of()
  plugins/tag/setup.php:105                          PluginTagTag::getCurrentItemtype()
  inc/plugin.class.php:144                           plugin_init_tag()
  inc/includes.php:115                               Plugin::load()
  index.php:57                                       include()

[2018-11-05 17:57:40] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined variable: CFG_GLPI
  Backtrace :
  index.php:108                                      
  ...hare/php/Zend/Loader/StandardAutoloader.php:291 include()
  ...hare/php/Zend/Loader/StandardAutoloader.php:232 Zend\Loader\StandardAutoloader->loadClass()
  :                                                  Zend\Loader\StandardAutoloader->autoload()
  :                                                  spl_autoload_call()
  plugins/tag/inc/tag.class.php:623                  is_subclass_of()
  plugins/tag/setup.php:105                          PluginTagTag::getCurrentItemtype()
  inc/plugin.class.php:144                           plugin_init_tag()
  inc/includes.php:115                               Plugin::load()
  index.php:57                                       include()

[2018-11-05 17:57:40] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined variable: CFG_GLPI
  Backtrace :
  index.php:146                                      
  ...hare/php/Zend/Loader/StandardAutoloader.php:291 include()
  ...hare/php/Zend/Loader/StandardAutoloader.php:232 Zend\Loader\StandardAutoloader->loadClass()
  :                                                  Zend\Loader\StandardAutoloader->autoload()
  :                                                  spl_autoload_call()
  plugins/tag/inc/tag.class.php:623                  is_subclass_of()
  plugins/tag/setup.php:105                          PluginTagTag::getCurrentItemtype()
  inc/plugin.class.php:144                           plugin_init_tag()
  inc/includes.php:115                               Plugin::load()
  index.php:57                                       include()

[2018-11-05 17:57:40] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined variable: CFG_GLPI
  Backtrace :
  index.php:150                                      
  ...hare/php/Zend/Loader/StandardAutoloader.php:291 include()
  ...hare/php/Zend/Loader/StandardAutoloader.php:232 Zend\Loader\StandardAutoloader->loadClass()
  :                                                  Zend\Loader\StandardAutoloader->autoload()
  :                                                  spl_autoload_call()
  plugins/tag/inc/tag.class.php:623                  is_subclass_of()
  plugins/tag/setup.php:105                          PluginTagTag::getCurrentItemtype()
  inc/plugin.class.php:144                           plugin_init_tag()
  inc/includes.php:115                               Plugin::load()
  index.php:57                                       include()

[2018-11-05 17:57:40] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined variable: CFG_GLPI
  Backtrace :
  index.php:162                                      
  ...hare/php/Zend/Loader/StandardAutoloader.php:291 include()
  ...hare/php/Zend/Loader/StandardAutoloader.php:232 Zend\Loader\StandardAutoloader->loadClass()
  :                                                  Zend\Loader\StandardAutoloader->autoload()
  :                                                  spl_autoload_call()
  plugins/tag/inc/tag.class.php:623                  is_subclass_of()
  plugins/tag/setup.php:105                          PluginTagTag::getCurrentItemtype()
  inc/plugin.class.php:144                           plugin_init_tag()
  inc/includes.php:115                               Plugin::load()
  index.php:57                                       include()

[2018-11-05 17:57:40] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined variable: CFG_GLPI
  Backtrace :
  index.php:206                                      
  ...hare/php/Zend/Loader/StandardAutoloader.php:291 include()
  ...hare/php/Zend/Loader/StandardAutoloader.php:232 Zend\Loader\StandardAutoloader->loadClass()
  :                                                  Zend\Loader\StandardAutoloader->autoload()
  :                                                  spl_autoload_call()
  plugins/tag/inc/tag.class.php:623                  is_subclass_of()
  plugins/tag/setup.php:105                          PluginTagTag::getCurrentItemtype()
  inc/plugin.class.php:144                           plugin_init_tag()
  inc/includes.php:115                               Plugin::load()
  index.php:57                                       include()

[2018-11-05 17:57:41] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/tag/inc/tag.class.php:614                  
  plugins/tag/setup.php:105                          PluginTagTag::getCurrentItemtype()
  inc/plugin.class.php:144                           plugin_init_tag()
  inc/includes.php:115                               Plugin::load()
  front/cron.php:38                                  include()

Hope it could help.

jfr

**Comment by tsmr** [comment]
Upgrade 9.4.2 - Tag 2.1.2 Same problems : 
- Cannot login into GLPI
- Error when logout (with CAS)
- Error in httpd/error.log

```
diff --git a/inc/tag.class.php b/inc/tag.class.php
index fac83ff..a2e29a0 100644
--- a/inc/tag.class.php
+++ b/inc/tag.class.php
@@ -1,3 +1,4 @@
+
 <?php
 class PluginTagTag extends CommonDropdown {
 
@@ -562,30 +563,31 @@ class PluginTagTag extends CommonDropdown {
     * @return mixed(string/boolean) false if not itemtype found, the string itemtype if found
     */
    public static function getCurrentItemtype() {
-      $itemtype = '';
-      if (preg_match('/\/plugins\/([a-zA-Z]+)\/front\/([a-zA-Z]+).form.php/',
-                     $_SERVER['PHP_SELF'], $matches)) {
-         $itemtype = 'plugin'.$matches[1].$matches[2];
-
-      } else if (preg_match('/([a-zA-Z]+).form.php/', $_SERVER['PHP_SELF'], $matches)) {
-         $itemtype = $matches[1];
-
-      } else if (preg_match('/\/plugins\/([a-zA-Z]+)\/front\/([a-zA-Z]+).php/',
-                            $_SERVER['PHP_SELF'], $matches)) {
-         $itemtype = 'plugin'.$matches[1].$matches[2];
-
-      } else if (preg_match('/([a-zA-Z]+).php/', $_SERVER['PHP_SELF'], $matches)) {
-         $itemtype = $matches[1];
-      }
+   
+      if((strpos($_SERVER['PHP_SELF'],'logout.php') == 0) 
+         || (strpos($_SERVER['PHP_SELF'],'login.php') == 0)) {
+         $itemtype = '';
+         if (preg_match('/\/plugins\/([a-zA-Z]+)\/front\/([a-zA-Z]+).form.php/',
+                        $_SERVER['PHP_SELF'], $matches)) {
+            $itemtype = 'plugin'.$matches[1].$matches[2];
+         } else if (preg_match('/\/front\/([a-zA-Z]+).form.php/', $_SERVER['PHP_SELF'], $matches)) {
+            $itemtype = $matches[1];
+         } else if (preg_match('/\/plugins\/([a-zA-Z]+)\/front\/([a-zA-Z]+).php/',
+                               $_SERVER['PHP_SELF'], $matches)) {
+            $itemtype = 'plugin'.$matches[1].$matches[2];
+         } else if (preg_match('/\/front\/([a-zA-Z]+).form.php/', $_SERVER['PHP_SELF'], $matches)) {
+            $itemtype = $matches[1];
+         }
 
-      if (!empty($itemtype)
-          && class_exists($itemtype)
-          && is_subclass_of($itemtype, "CommonDBTM")) {
-         // instanciate itemtype (to retrieve camelcase)
-         $item = new $itemtype;
-         return $item->getType();
+         if (!empty($itemtype)
+            && $itemtype != 'allassets'
+            && class_exists($itemtype)
+            && is_subclass_of($itemtype, "CommonDBTM", true)) {
+            // instanciate itemtype (to retrieve camelcase)
+            $item = new $itemtype;
+            return $item->getType();
+         }
       }
-
       return false;
    }
 }
```

**Comment by cedric-anne** [comment]
Hi @tsmr ,

Do you think it is possible to have a more flexible solution ? Checking `(strpos($_SERVER['PHP_SELF'],'login.php') == 0) `  is a really specific check that will not fix other potential problems.

By the way, if you have errors related to Zend Autoload, it's not only related to tag plugin itself. Which other plugins are you using ?

Regards

**Comment by gabrielpetrone** [comment]
Version 2.5.0 and GLPI 9.4.4 still with this issue.
But now the solution by @tsmr is on line 681, and worked fine.

**Comment by OscarBeiro** [comment]
Version 2.6.0 and GLPI 9.4.2 and the same issue.
This seems to affect to CentOS and its Zend Framework only.

As GLPI 9.5 is moving to Laminas I guess this will remain unfixed.

By the way, thanks @tsmr for your patch. Lines have changed but the solution still applies.
